description: "Addressability"
publisher: "Various"
keywords: "Addressability"
title: "Addressability"

name: "Addressability"

email: "email@addressability.com"

permalink: /:categories/:title/

plugins:
  - jekyll-redirect-from
